# Generated by Django 4.1.2 on 2023-03-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=50, null=True)),
                ('Image', models.ImageField(upload_to='')),
                ('siege', models.CharField(default='Yaounde', max_length=30)),
                ('telephone', models.CharField(default='678963685', max_length=30)),
                ('description', models.CharField(max_length=40, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
