# Generated by Django 4.1.2 on 2023-03-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=30)),
                ('email2', models.EmailField(blank=True, max_length=254)),
                ('phone2', models.PositiveIntegerField(default='')),
                ('suject2', models.CharField(max_length=30)),
                ('description2', models.TextField(default='votre probleme')),
            ],
        ),
    ]
