# Generated by Django 4.1.2 on 2023-03-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vente', '0004_delete_crud_alter_commentaireclient_phone2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentaireClient',
            new_name='Commentaire',
        ),
    ]
