# Generated by Django 4.1.2 on 2023-03-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vente', '0008_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
