# Generated by Django 4.1.2 on 2022-12-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_chaussure_alter_crud_author_alter_crud_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaussure',
            name='name2',
            field=models.CharField(max_length=30),
        ),
    ]
