# Generated by Django 4.0.2 on 2023-03-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_chaussure_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crud2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=50)),
                ('picture2', models.ImageField(upload_to='')),
                ('author2', models.CharField(default='bien chaud', max_length=30)),
                ('email2', models.EmailField(blank=True, max_length=254)),
                ('description2', models.PositiveIntegerField(default='0')),
            ],
        ),
    ]
